name: Release
on:
 push:
   tags:
     - '*'

jobs:
 lint:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v4
       with:
         node-version: '20.x'
         scope: '@octocat'
     - run: yarn
     - run: yarn lint

 build:
   runs-on: ubuntu-latest
   needs: lint
   steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v4
       with:
         node-version: '20.x'
         scope: '@octocat'
     - run: yarn
     - run: yarn build
     - name: Upload build artifacts
       uses: actions/upload-artifact@v3
       with:
         name: dist
         path: dist/

 release:
   runs-on: ubuntu-latest
   permissions:
     contents: write
   needs: build
   steps:
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0
     - uses: actions/download-artifact@v3
       with:
         name: dist
         path: dist/
     - name: Install github cli
       run: sudo apt-get install gh
     - name: Install conventional-changelog-cli
       run: npm install -g conventional-changelog-cli
     - name: Generate release notes
       run: conventional-changelog-cli -p angular -r 1 > RELEASE_NOTES.md
     - name: Create github release
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         if ! gh release view ${{ github.ref_name }} &>/dev/null; then
           gh release create ${{ github.ref_name }} \
             --title "${{ github.ref_name }}" \
             --notes-file RELEASE_NOTES.md
         else
           echo "Release ${{ github.ref_name }} already exists"
         fi
